@baseUrl = http://localhost:4004

###
GET {{baseUrl}}/order-service/Products(29f332f4-4a7a-4b93-b2bc-074ef0400cf6)
Content-Type: application/json


###
POST {{baseUrl}}/order-service/Products
Content-Type: application/json

{
    "name": "i5 6600",
    "price": 699.99,
    "manufacturer_ID": "b093e2f8-3cd9-4d67-813a-b7b74a8c8c45",
    "typeOfProduct": "CPU",
    "stock": 100
}

###
PUT {{baseUrl}}/order-service/Products(4df0b891-2de9-4e7e-9b75-41096b7f0d0b)
Content-Type: application/json

{
    "name": "i5 660000000",
    "price": 699.99,
    "manufacturer_ID": "b093e2f8-3cd9-4d67-813a-b7b74a8c8c45",
    "typeOfProduct": "CPU",
    "stock": 100
}

###
DELETE {{baseUrl}}/order-service/Products(4df0b891-2de9-4e7e-9b75-41096b7f0d0b)
